platform :ios, '9.0'

target 'magnetX' do
  
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxNetwork'
  pod 'RxDataSources'
  pod 'RxSwiftExt'
  pod 'Differentiator'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'EachNavigationBar'
  pod 'FSPagerView'
  pod 'WCDB.swift'
  pod 'WKWebViewJavascriptBridge'
  pod 'IQKeyboardManagerSwift'
  pod 'MJRefresh'
  pod 'Ono'
  pod 'LTScrollView'
  pod 'CocoaChainKit'
  pod 'SkeletonView'
  pod 'Toast-Swift'
  pod 'ColorThiefSwift'

end
